# avec un import de definitions, RabbitMQ ne cree pas d'utilisateur par defaut
definitions.import_backend = local_filesystem
definitions.local.path = /etc/rabbitmq/definitions
# sinon le seuil memoire se base sur la RAM de la VM
total_memory_available_override_value = 400MB
